import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    blocks: [
      {
        id: '1',
        img: 'VKO-Van-Bodies-LBW-Schnellstrasse 2.png',
        title: 'СТО “Шмітц Каргобул Україна', 
        address: '22, Кільцева дорога, Київ, 03134', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'green',
        svgColor: '#6FCF97',
        stripText: 'фінанси',
        category: 'finance',
      },
      {
        id: '2',
        img: 'd02fb87f 2.png', 
        title: 'БЦ “Престиж”', 
        address: 'бульвар Вацлава Гавела, 6з, Київ, 03067', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'blue',
        svgColor: '#77A0E2',
        stripText: 'нерухомість',
        category: 'realty',
      },
      {
        id: '3', 
        img: 'VKO-Van-Bodies-LBW-Schnellstrasse 2.png',
        title: 'СТО “Шмітц Каргобул Україна', 
        address: '22, Кільцева дорога, Київ, 03134', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'blue',
        svgColor: '#77A0E2',
        stripText: 'нерухомість',
        category: 'realty',
      },
      {
        id: '4', 
        img: 'd02fb87f 2.png',
        title: 'БЦ “Престиж”', 
        address: 'бульвар Вацлава Гавела, 6з, Київ, 03067', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'green',
        svgColor: '#6FCF97',
        stripText: 'фінанси',
        category: 'finance',
      },
      {
        id: '5',
        img: 'VKO-Van-Bodies-LBW-Schnellstrasse 2.png',
        title: '11111', 
        address: '22, Кільцева дорога, Київ, 03134', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'green',
        svgColor: '#6FCF97',
        stripText: 'фінанси',
        category: 'finance',
      },
      {
        id: '6',
        img: 'd02fb87f 2.png', 
        title: '222222', 
        address: 'бульвар Вацлава Гавела, 6з, Київ, 03067', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'blue',
        svgColor: '#77A0E2',
        stripText: 'нерухомість',
        category: 'realty',
      },
      {
        id: '7', 
        img: 'VKO-Van-Bodies-LBW-Schnellstrasse 2.png',
        title: '333333', 
        address: '22, Кільцева дорога, Київ, 03134', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'blue',
        svgColor: '#77A0E2',
        stripText: 'нерухомість',
        category: 'realty',
      },
      {
        id: '8', 
        img: 'd02fb87f 2.png',
        title: '4444444', 
        address: 'бульвар Вацлава Гавела, 6з, Київ, 03067', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'green',
        svgColor: '#6FCF97',
        stripText: 'фінанси',
        category: 'finance',
      },
      {
        id: '9',
        img: 'VKO-Van-Bodies-LBW-Schnellstrasse 2.png',
        title: '555555', 
        address: '22, Кільцева дорога, Київ, 03134', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'green',
        svgColor: '#6FCF97',
        stripText: 'фінанси',
        category: 'finance',
      },
      {
        id: '10',
        img: 'd02fb87f 2.png', 
        title: '6666666', 
        address: 'бульвар Вацлава Гавела, 6з, Київ, 03067', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'blue',
        svgColor: '#77A0E2',
        stripText: 'нерухомість',
        category: 'realty',
      },
      {
        id: '11', 
        img: 'VKO-Van-Bodies-LBW-Schnellstrasse 2.png',
        title: '77777777', 
        address: '22, Кільцева дорога, Київ, 03134', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'blue',
        svgColor: '#77A0E2',
        stripText: 'нерухомість',
        category: 'realty',
      },
      {
        id: '12', 
        img: 'd02fb87f 2.png',
        title: '8888888', 
        address: 'бульвар Вацлава Гавела, 6з, Київ, 03067', 
        client: 'Шмитц Каргобул Украина ООО', 
        color: 'green',
        svgColor: '#6FCF97',
        stripText: 'фінанси',
        category: 'finance',
      },
    ],
    currentPage: 0,
  },
  mutations: {
    changeCurrentPage(state, payload) {
      state.currentPage += payload;
    },
    resetCurrentPage(state) {
      state.currentPage = 0;
    }
  },
  actions: {
  },
  modules: {
  }
})
